#!/bin/bash
# 
# post-receive for staging server
# use with any bd or desby project
# @author frankrue@gmail.com
# 


# dynamic determination (maybe future use?)
############################################

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    case "$branch" in

	    staging)

            # is this a bare repo?
            if [ $(git rev-parse --is-bare-repository) = true ]
            then
              # get the pwd
                REPOSITORY_BASENAME=$(basename "$PWD")
            else
              # get the parent dir
                REPOSITORY_BASENAME=$(basename $(readlink -nf "$PWD"/..))
            fi
            # remove the '.git' from the end
            REPOSITORY_BASENAME=${REPOSITORY_BASENAME%.git}

            # make a directory name
            DIRECTORY=/var/app/current/public/$REPOSITORY_BASENAME
            if [ ! -d "$DIRECTORY" ]; then
                mkdir $DIRECTORY
            fi

            # set the work tree to a folder in the www root
            GIT_WORK_TREE=$DIRECTORY/ git checkout develop -f
	    			;;

	    *)			# other branches
	    			
	    			;;

	esac
done
